### ISSUE TITLE
First cell representing the name of the micro service shall itself be color coded based on  the current state of the build.

### ISSUE THREAD

**Issue by beginsmauel** [ERS-HCL/metrics#2]
The cell representing the name of the micro service shall itself be color coded based on  the current state of the build.

Micro Service | # Build Failures / Week (last 7 days) | Mean time to resolve Build Failures | # Defects | Avg # Commits per days (last 7 days)
-- | -- | -- | -- | --
CatalogMS | 10 (Drill down) | 2 hrs | 10 (Drill Down) | 10 (Drill Down)
Service   2 |   |   |   |  
…..n |   |   |   |

**Comment by sitharthan** [comment]
Addressed this issue : Implemented text color as **GREEN** if the build is **Success**. Same as implemented text color as **RED** if the build is **Failure**. And Highlighted text color as **Blue** for Build Number with link. **Link** is redirect to current **Build** page details.
