### ISSUE TITLE
Drill down on the Micro Service shall proceed into the 2nd level of information from different resources

### ISSUE THREAD

**Issue by beginsmauel** [ERS-HCL/metrics#3]
1.	Drill down on the Micro Service shall proceed into the Jenkins for the micro service
2.	Drill Downs for the other columns shall show the tabular data shown below. Since the drill downs only contain one micro service, the table can be oriented anyway.

**Defects**

Micro Service | #defects (day 1/today) | Upto 7 days | Trend | Avg. Daily Change
-- | -- | -- | -- | --
CatalogMS | 10 (Link goes into TDP) |   | Up/Down |  

**Builds**

Micro Service | Recent Build Time | Next recent build time | Upto 5 Recent builds | Mean time to resolve build failures for last 7 days
-- | -- | -- | -- | --
CatalogMS | Success/Fail (Link goes into Jenkins) | Success/Fail |   |  

**Commits**

Micro Service | #commits (day 1/today) | Upto 7 days | Trend | Avg. Daily Change
-- | -- | -- | -- | --
CatalogMS | 10 (Link goes into TDP) |   | Up/Down |

**Comment by sitharthan** [comment]
Implementation done and shown the demo to Senior folks
